### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cmrberry** [cmrberry/test-rename#12]
This is the main ticket for XX milestone.

#### Done

This ticket/milestone is done when we successfully distribute XX Team revenue to ~users as part of payday. The six ~users we are targeting for the first distribution are: XXXXXX

##### National Identity

- [x] deploy schema and Python for storing national identity for ~users: #3976
 - [x] implement symmetric encryption: #3998 
 - [x] add countries: ~~#3999~~ &rarr; #4027
 - [x] implement encrypted national identities: ~~#4000~~ &rarr; #4028
 - [x] [un]verifying identities: ~~#4001~~ &rarr; #4031
 - [x] clearing identities: ~~#4002~~ &rarr; #4032
 - [x] has_verified_identity: ~~#4003~~ &rarr; #4033
- [x] implement fake data for participant identities: #4006 
- [x] deploy UI for publicly displaying country info of ~users: #4007
- [x] deploy UI for storing national identity for ~users: ~~#4008~~ &rarr; #4034
- [x] 👾  bonus PRs: #4035 #4036

##### Takes

 - [ ] make room for team changes: #4037
 - [ ] plumb takes: #4023
 - [ ] plumb membership: #4024
 - [ ] add takes distribution to payday: #4025
 - [ ] implement takes UI: #4026

##### Finish!

 - [ ] use UI to add identities
 - [ ] use Python API to verify identities
 - [ ] use Python API to issue takes for Team XX
 - [ ] use Python API to add members to Team XX
 - [ ] use UI to set takes
 - [ ] run payday!

**Comment by cmrberry** [comment]
@testberry - Hi!
